name: jubjub
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.1.1
  toast: ^0.1.5
  http: ^0.12.1
  get_it: ^4.0.1
  chewie: ^0.9.10
  sqflite: ^1.3.0
  archive: ^2.0.13
  photo_view: ^0.9.2
  expandable: ^4.1.3
  googleapis: ^0.54.0  
  file_picker: ^1.7.1
  flutter_mobx: ^1.1.0
  video_player: ^0.10.9
  path_provider: ^1.5.1  
  dynamic_theme: ^1.0.1
  audioplayers: ^0.15.1 
  firebase_auth: ^0.16.0      
  google_sign_in: ^4.4.4
  cupertino_icons: ^0.1.2
  googleapis_auth: ^0.2.11  
  percent_indicator: ^2.1.5
  shared_preferences: ^0.5.7
  progress_indicators: ^0.1.5
  permission_handler: ^5.0.1+1
  cached_network_image: ^2.2.0  
  flutter_material_color_picker: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.0
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  assets:
    - assets/sql/
    - assets/images/
  uses-material-design: true

scripts:
  build: 
    - flutter pub run build_runner build --delete-conflicting-outputs
  build-apk: 
    - flutter pub run build_runner build --delete-conflicting-outputs
    - flutter pub run flutter_launcher_icons:main
    - flutter build apk
  copy-database:
    - adb root
    - adb -e pull /data/data/com.salominho.jubjub/databases/jubjub_database.db %USERPROFILE%\Desktop\
